Update
YunoHost-Apps/minio_ynh pull request #64
Opened 2023-11-27 17:32 UTC by ericgaspar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-11-27 17:32 UTC, ericgaspar commented
!testme

2024-03-23 10:26 UTC, fflorent requested changes

2024-03-23 10:26 UTC, fflorent commented on manifest.toml
> +        arm64.url = "https://dl.min.io/server/minio/release/darwin-arm64/minio.RELEASE.2023-11-20T22-40-07Z"
```suggestion
        arm64.url = "https://dl.min.io/server/minio/release/linux-arm64/minio.RELEASE.2023-11-20T22-40-07Z"
```

2025-02-28 12:32 UTC, ericgaspar commented
superseded with #70

2025-02-28 12:32 UTC, closed without merging